### ISSUE TITLE
L1CSM Tom's comments on 2020-12-31

### ISSUE THREAD

**Issue by italobusi** [haomianzheng/IETF-ACTN-YANG-Model#78]
> I-D has five authors  YANG module has six AD may complain
> 
> YANG import need reference clauses - they used to have them but were removed
> 
> YANG contact information is the wrong format and lacks web and list references
> 
> l1types must be a Normative reference
> 
> MEF 63 is much referenced in the YANG module but inconsistently sometimes just as that sometimes with the title - consistency is good, I prefer the latter
> 
> YANG identity for performance reference MEF 63 - I would have expected an ITU-T reference such as G.826 which other I-D use or one of the M. series
> 
> YANG groupings are ...-attribute or .....-attributes consistency is good, I prefer the latter
> 
> YANG time-interval - is there a sensible default or worthwhile guidance in the description beyond the e.g.?
> 
> YANG endpoint-1 and endpoint-2 - must they be different id in which case YANG can enforce that
> 
> YANG id is a string of unconstrained length and character set; this is what most authors do but I wish that YANG had a suitable type for identifiers as SMI has
> 
> YANG case ITU could do with a reference ideally to ITU-T rather than to l1types
> 
> /an unique/a unique/ (English is perverse!)
> 
> YANG description clauses the text should start with a Capital letter 
> 
> examples are usually at the end and in an Appendix, which is then by default Informative

See: https://mailarchive.ietf.org/arch/msg/ccamp/tdZg_YsgGscL0j8IrIFxY8BnDEY/

**Comment by haomianzheng** [comment]
See inline...
> > I-D has five authors  YANG module has six AD may complain 

Moved KK Lee to contributor; done in xml. 
> > YANG import need reference clauses - they used to have them but were removed

added, see https://github.com/haomianzheng/IETF-ACTN-YANG-Model/pull/80
> > YANG contact information is the wrong format and lacks web and list references

added, see https://github.com/haomianzheng/IETF-ACTN-YANG-Model/pull/80
> > l1types must be a Normative reference

done in xml. 
> > MEF 63 is much referenced in the YANG module but inconsistently sometimes just as that sometimes with the title - consistency is good, I prefer the latter

added, see https://github.com/haomianzheng/IETF-ACTN-YANG-Model/pull/80
> > YANG identity for performance reference MEF 63 - I would have expected an ITU-T reference such as G.826 which other I-D use or one of the M. series

I prefer to keep as is, as the objective of L1CSM is to align with MEF63. The ITU-T reference can be used in other documents, such as pm-yang. 
> > YANG groupings are ...-attribute or .....-attributes consistency is good, I prefer the latter

fixed, see https://github.com/haomianzheng/IETF-ACTN-YANG-Model/pull/80
> > YANG time-interval - is there a sensible default or worthwhile guidance in the description beyond the e.g.?

Personally I think on CMI it should be fully customized, prefer to keep as is. 
> > YANG endpoint-1 and endpoint-2 - must they be different id in which case YANG can enforce that

should be different end point for any services provided. A 'must' statement is added. See https://github.com/haomianzheng/IETF-ACTN-YANG-Model/pull/80
> > YANG id is a string of unconstrained length and character set; this is what most authors do but I wish that YANG had a suitable type for identifiers as SMI has

Personally I think on CMI it should be fully customized, prefer to keep as is. 
> > YANG case ITU could do with a reference ideally to ITU-T rather than to l1types

Unfortunately we don't have a pointer to ITU-T (or to G.709?). At least referring to l1-types is not misleading. Prefer to keep as is. 
> > /an unique/a unique/ (English is perverse!)

fixed, see https://github.com/haomianzheng/IETF-ACTN-YANG-Model/pull/80
> > YANG description clauses the text should start with a Capital letter

fixed, see https://github.com/haomianzheng/IETF-ACTN-YANG-Model/pull/80
> > examples are usually at the end and in an Appendix, which is then by default Informative. 
fixed in xml. 
> 
> See: https://mailarchive.ietf.org/arch/msg/ccamp/tdZg_YsgGscL0j8IrIFxY8BnDEY/

**Comment by italobusi** [comment]
> > > YANG identity for performance reference MEF 63 - I would have expected an ITU-T reference such as G.826 which other I-D use or one of the M. series
> 
> I prefer to keep as is, as the objective of L1CSM is to align with MEF63. The ITU-T reference can be used in other documents, such as pm-yang.
> 

IMHO, this should be tracked as an open issue.

The PM metrics for L1CSM are defined by MEF 63 but it would be worthwhile reconciling them with ITU-T definitions, which are applicable to other models.

> > > YANG time-interval - is there a sensible default or worthwhile guidance in the description beyond the e.g.?
> 
> Personally I think on CMI it should be fully customized, prefer to keep as is.
> 

@italobusi : check MEF 63 definition

> > > YANG id is a string of unconstrained length and character set; this is what most authors do but I wish that YANG had a suitable type for identifiers as SMI has
> 
> Personally I think on CMI it should be fully customized, prefer to keep as is.
> 

@italobusi : check MEF 63 definition

> > > YANG case ITU could do with a reference ideally to ITU-T rather than to l1types
> 
> Unfortunately we don't have a pointer to ITU-T (or to G.709?). At least referring to l1-types is not misleading. Prefer to keep as is.
> 

I think that the YANG case ITU is to configure the client-signal, as defined by l1-types, whose definitions are derived from ITU-T G.709
